name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

permissions:
  contents: read

env:
  KCOV_VERSION: 42

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0  # most recent stable

      - name: Check formatting
        run: zig fmt --check .

  test:
    name: Test / Zig ${{ matrix.zig-version }} / ${{ matrix.os}}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allow-fail }}
    strategy:
      matrix:
        zig-version: ['0.11.0']
        os: [ubuntu-latest, windows-latest]
        allow-fail: [false]
        include:
          - zig-version: master
            os: ubuntu-latest
            allow-fail: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cached kcov
        id: kcov
        uses: actions/cache@v3
        with:
          path: ~/kcov
          key: ${{ runner.os }}-kcov-${{ env.KCOV_VERSION }}

      - name: Build kcov
        if: steps.kcov.outputs.cache-hit != 'true'
        shell: bash
        run: |
          mkdir ~/src ~/kcov
          URL=https://github.com/SimonKagstrom/kcov/archive/refs/tags/v$KCOV_VERSION.tar.gz
          curl -L "$URL" | tar xvzf - -C ~/src
          cd ~/src/kcov-"$KCOV_VERSION"
          # Hack:
          # Workaround for undefined symbol "assert" while building on macOS.
          sed -i -e '/ assert(/d' src/engines/mach-engine.cc

          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$HOME/kcov"  .
          make
          make install

      - name: Add kcov to PATH
        shell: bash
        run: |
          echo "$HOME/kcov/bin" >> "$GITHUB_PATH"

      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Run tests
        run: zig build test -Dtest-cover

      - name: Coverage
        uses: codecov/codecov-action@v3
